[package]
name = "engine"
authors.workspace = true
version.workspace = true
edition.workspace = true

[dependencies]
approx = "0.5.1"
log = "0.4"
ndarray = { version = "0.16.1", features = ["approx"] }
